site_name: OpenRetina Docs

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Media queries for color scheme switch
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: assets/openretina_logo.png
  favicon: assets/openretina_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.indexes

plugins:
  - mkdocstrings
  - search
  - social

site_url: https://open-retina.org

site_description: "todo fallback site description"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Home: index.md
  - Package documentation:
    - package_docs/index.md
    - Data Input/Output:
      - Hoefling et al., 2024: package_docs/data_io/hoefling_2024.md
  - FAQs: faq.md

repo_url: https://github.com/open-retina/open-retina
repo_name: open-retina

extra_css:
  - assets/stylesheets/extra.css
