filter_cell_types: true
cell_types_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
chirp_qi: 0.35
d_qi: 0.6
qi_logic: "and"
filter_counts: true
count_threshold: 10
classifier_confidence: 0.3
verbose: true