# Config file for loading white noise data from the Sridhar et al. (2025) dataset
# Data originally from: https://gin.g-node.org/gollischlab/Sridhar_Gollisch_2025_Marmoset_RGC_Responses_Naturalistic_Movies
# Paper: https://www.biorxiv.org/content/10.1101/2024.03.05.583449v2


_target_: openretina.data_io.sridhar_2025.dataloaders.white_noise_loader
_convert_: object
basepath: ''
files:
  '01': 'responses/cell_responses_01_wn.pkl'
  '02': 'responses/cell_responses_02_wn.pkl'
  '04': 'responses/cell_responses_04_wn.pkl'

big_crops:
  '01': [35, 35, 55, 55]
  '02': [35, 35, 55, 55]
  '04': [35, 35, 55, 55]

train_image_path:
  '01': 'non_repeating_stimuli_1'
  '02': 'non_repeating_stimuli_1'
  '04': 'non_repeating_stimuli_2'

test_image_path:
  '01': 'repeating_stimuli_1'
  '02': 'repeating_stimuli_1'
  '04': 'repeating_stimuli_2'

excluded_cells:
  '01': []
  '02': []
  '03': []
  '04': []

batch_size: 16
seed: null
train_frac: 0.8
subsample: 1
crop: 0
use_cache: True
cache_maxsize: 1
num_of_trials_to_use: null
start_using_trial: 0
num_of_frames: 30
num_of_hidden_frames: 5
temporal_dilation: 1
hidden_temporal_dilation: 1
cell_index: null
device: 'cuda'
time_chunk_size: 100
num_of_layers: 1
retina_specific_crops: True
extra_frame: 0
hard_coded: null
chunked_sampling: True



