_target_: openretina.models.core_readout.GRUCoreReadout
_convert_: all
in_channels: 2
hidden_channels: [32, 64]
temporal_kernel_sizes: [21, 11]
spatial_kernel_sizes: [11, 5]
in_shape: [2, 150, 18, 16]
n_neurons_dict: ???
core_gamma_hidden: 0.0
core_gamma_input: 0.3
core_gamma_in_sparse: 1.0
core_gamma_temporal: 40.0
core_bias: true
core_input_padding: false
core_hidden_padding: true
core_use_gru: false
core_use_projections: true
readout_scale: true
readout_bias: true
readout_gaussian_masks: true
readout_gaussian_mean_scale: 6.0
readout_gaussian_var_scale: 4.0
readout_positive: true
readout_gamma: 0.4
readout_gamma_masks: 0.1
readout_reg_avg: false
learning_rate: 0.01
core_gru_kwargs: null