_target_: openretina.models.core_readout.CoreReadout
_convert_: object

# core
in_shape: ??? # needs to be set before training
hidden_channels: [16, 16]
temporal_kernel_sizes: [21, 11]
spatial_kernel_sizes: [11, 5]
core_gamma_input: 0.0
core_gamma_in_sparse: 0.0
core_gamma_hidden: 0.0
core_gamma_temporal: 40.0

# readout
n_neurons_dict: ??? # needs to be set before training
readout_scale: True
readout_bias: True
readout_gaussian_masks: True
readout_gaussian_mean_scale: 6.0
readout_gaussian_var_scale: 4.0
readout_positive: True
readout_gamma: 0.4

# training
learning_rate: 0.01
cut_first_n_frames_in_core: 30
dropout_rate: 0.0
