wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  offline: False
  project: ??? # Needs to be set!
  version: ${now:%Y-%m-%d_%H-%M-%S}
  log_model: "all" # Checkpoints get uploaded to wandb
  save_dir: "${paths.output_dir}"
