defaults:
  - _self_
  - quality_checks: hoefling_2024

exp_name: example_core_readout_low_res_filtered
data_folder: "/gpfs01/euler/data/SharedFiles/projects/TP12/"
movies_filename: "2024-01-11_movies_dict_8c18928.pkl"
responses_filename: "2024-08-14_neuron_data_responses_484c12d_djimaging.h5"
save_folder: exp/
max_epochs: 100
seed: 42

core_readout:
  in_channels: 2
  features_core: [16, 16]
  temporal_kernel_sizes: [21, 11]
  spatial_kernel_sizes: [11, 5]
  in_shape_readout: [16, 120, 18, 16]
  scale: True
  bias: True
  gaussian_masks: True
  gaussian_mean_scale: 6.0
  gaussian_var_scale: 4.0
  positive: True
  gamma_readout: 0.4
  learning_rate: 0.01
  cut_first_n_frames_in_core: 30
  dropout_rate: 0.0

natmov_dataloader:
    validation_clip_indices: [0, 4, 10, 11, 18, 30, 45, 62, 67, 77, 79, 80, 81, 83, 95]
    train_chunk_size: 100

dataloader:
  batch_size: null
  num_workers: 4

loggers:
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
  tensorboard:
    _target_: lightning.pytorch.loggers.TensorBoardLogger

training_callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    monitor: "val_correlation"
    min_delta: 0.001
    patience: 15
    verbose: True
    mode: "max"
  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: "epoch"
    log_momentum: true
    log_weight_decay: true

