exp_name: example_core_readout
data_folder: /gpfs01/euler/data/SharedFiles/projects/TP12/
save_folder: exp/
max_epochs: 100

core_readout:
  in_channels: 2
  features_core: [16, 16]
  temporal_kernel_sizes: [21, 11]
  spatial_kernel_sizes: [11, 5]
  in_shape: [2, 750, 18, 16]
  scale: True
  bias: True
  gaussian_masks: True
  gaussian_mean_scale: 6.0
  gaussian_var_scale: 4.0
  positive: True
  gamma_readout: 0.4
  learning_rate: 0.003

dataloader:
  batch_size: null
  num_workers: 0

loggers:
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
  tensorboard:
    _target_: lightning.pytorch.loggers.TensorBoardLogger

training_callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    monitor: "val_correlation"
    min_delta: 0.01
    patience: 15
    verbose: True
    mode: "max"
