exp_name: example_core_readout
data_folder: /gpfs01/euler/data/SharedFiles/projects/TP12/
save_folder: exp/
max_epochs: 100

core_readout:
  in_channels: 2
  features_core: [16, 16, 16, 16]
  temporal_kernel_sizes: [16, 16, 8, 8]
  spatial_kernel_sizes: [16, 16, 8, 8]
  in_shape: [2, 150, 72, 64]
  scale: True
  bias: True
  gaussian_masks: True
  gaussian_mean_scale: 6.0
  gaussian_var_scale: 4.0
  gamma_readout: 0.4
  learning_rate: 0.01
  maxpool_every_n_layers: 2
  cut_first_n_frames_in_core: 30
  dropout_rate: 0.0
  # positive: True  # to force positive readout features
  # device: "cuda"
  # downsample_input_kernel_size: [1, 4, 4]  # to reproduce Hoefling input size of 18x16px

dataloader:
  batch_size: null
  num_workers: 8

loggers:
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
  tensorboard:
    _target_: lightning.pytorch.loggers.TensorBoardLogger

training_callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    monitor: "val_correlation"
    min_delta: 0.001
    patience: 15
    verbose: True
    mode: "max"
