defaults:
  - data_io: hoefling_2024
  - quality_checks: hoefling_2024
  - dataloader: hoefling_2024
  - model: base_core_readout
  - training_callbacks:
    - early_stopping
    - lr_monitor
    - model_checkpoint
  - logger:
    - tensorboard
    - csv
  - trainer: default_deterministic
  - hydra: default
  - _self_ # values in this config will overwrite the defaults

exp_name: hoefling_2024_core_readout_high_res_filtered
seed: 42
check_stimuli_responses_match: false

dataloader:
  batch_size: 64


model:
  in_shape: [2, 150, 72, 64]
  hidden_channels: [16, 16, 16, 16]
  temporal_kernel_sizes: [15, 15, 7, 7]
  spatial_kernel_sizes: [15, 15, 7, 7]
  core_hidden_padding: true
  core_input_padding: true
  cut_first_n_frames_in_core: 30
  maxpool_every_n_layers: 2
  # downsample_input_kernel_size: [1, 4, 4]  # to reproduce 18x16px lowres input

paths:
  load_model_path: null  # e.g. hoefling_2024_base_high_res or path to a .ckpt model
  cache_dir: ${oc.env:OPENRETINA_CACHE_DIRECTORY} # Remote files are downloaded to this location
  data_dir: ${paths.cache_dir}/data/ # Folder where local files are read from.
  log_dir: "." # Used as parent for output_dir. Will store train logs.
  output_dir: ${hydra:runtime.output_dir} # Modify subpaths in the "hydra/default.yaml" config
  movies_path: "https://huggingface.co/datasets/open-retina/open-retina/resolve/main/euler_lab/hoefling_2024/stimuli/rgc_natstim_72x64_joint_normalized_2024-10-11.zip"
  responses_path: "https://huggingface.co/datasets/open-retina/open-retina/resolve/main/euler_lab/hoefling_2024/responses/rgc_natstim_2024-08-14.zip"

matmul_precision:
  _target_: torch.set_float32_matmul_precision
  precision: medium


trainer:
  max_epochs: 100
  accumulate_grad_batches: 10
  gradient_clip_val: 1
  precision: 16-mixed

only_train_readout: false # whether or not to freeze core parameters and only train readout (eg. when finetuning model to new data)
