defaults:
  - data_io: ??? # For new data, create data_io config and put its name here
  - dataloader: # For new data, create dataloader config and put its name here
  - model: base_core_readout
  - training_callbacks:
    - early_stopping
    - lr_monitor
    - model_checkpoint
  - logger:
    - tensorboard
    - csv
  - trainer: default_deterministic
  - hydra: default
  - _self_ # values in this config will overwrite the defaults

exp_name: ??? # Required 
seed: 42
check_stimuli_responses_match: false

data:
  root_dir: null # Choose the location of the root directory for the project
  data_dir: ${data.root_dir}/... # Choose the location of the data. Should be used in data_io functions.
  output_dir: ${data.root_dir}/openretina_assets/runs

# Overwrite model defaults with specifics for the current data input format
model:
  in_shape: ???
  hidden_channels: ???
  spatial_kernel_sizes: ??? 
  # Can over-ride further model defaults here. 


